version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:lts

jobs:
  lint-and-build:
    executor: node
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: NPM install
          command: |
            echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > ./.npmrc
            npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run build

workflows:
  version: 2
  build-and-test:
    jobs:
      - lint-and-build:
          context: NPM_TOKEN
